-- Oracle Database Schema for Biblioteca Virtual
-- Sistema de Préstamo de Libros

-- Create Users table
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL CHECK (role IN ('bibliotecario', 'usuario')),
    email_verified_at TIMESTAMP NULL,
    remember_token VARCHAR2(100) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Books table
CREATE TABLE books (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255) NOT NULL,
    author VARCHAR2(255) NOT NULL,
    isbn VARCHAR2(13) UNIQUE NOT NULL,
    description CLOB NULL,
    category VARCHAR2(100) NOT NULL,
    quantity NUMBER DEFAULT 1,
    available_quantity NUMBER DEFAULT 1,
    location VARCHAR2(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create Loans table
CREATE TABLE loans (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    book_id NUMBER NOT NULL,
    loan_date DATE NOT NULL,
    due_date DATE NOT NULL,
    return_date DATE NULL,
    status VARCHAR2(20) DEFAULT 'active' CHECK (status IN ('active', 'returned', 'overdue')),
    notes CLOB NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_loans_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_loans_book FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);

-- Create indexes for better performance
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_books_isbn ON books(isbn);
CREATE INDEX idx_books_category ON books(category);
CREATE INDEX idx_books_available ON books(available_quantity);
CREATE INDEX idx_loans_user_id ON loans(user_id);
CREATE INDEX idx_loans_book_id ON loans(book_id);
CREATE INDEX idx_loans_status ON loans(status);
CREATE INDEX idx_loans_due_date ON loans(due_date);
CREATE INDEX idx_loans_loan_date ON loans(loan_date);

-- Create sequences for ID generation (if not using IDENTITY)
-- CREATE SEQUENCE users_seq START WITH 1 INCREMENT BY 1;
-- CREATE SEQUENCE books_seq START WITH 1 INCREMENT BY 1;
-- CREATE SEQUENCE loans_seq START WITH 1 INCREMENT BY 1;

-- Create triggers for updated_at timestamps
CREATE OR REPLACE TRIGGER users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER books_updated_at
    BEFORE UPDATE ON books
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER loans_updated_at
    BEFORE UPDATE ON loans
    FOR EACH ROW
BEGIN
    :NEW.updated_at := CURRENT_TIMESTAMP;
END;
/

-- Insert sample data
INSERT INTO users (name, email, password, role) VALUES
('Admin Bibliotecario', 'admin@biblioteca.com', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'bibliotecario');

INSERT INTO books (title, author, isbn, description, category, quantity, available_quantity, location) VALUES
('El Quijote', 'Miguel de Cervantes', '9788491051185', 'Obra maestra de la literatura española', 'Clásico', 5, 5, 'Estante A1'),
('Cien años de soledad', 'Gabriel García Márquez', '9788497592208', 'Realismo mágico latinoamericano', 'Literatura', 3, 3, 'Estante B2'),
('Don Juan Tenorio', 'José Zorrilla', '9788420733745', 'Drama romántico español', 'Teatro', 2, 2, 'Estante C3');


